CREATE TABLE `Scope` (
    `Id` VARCHAR(36) NOT NULL,
    `Label` VARCHAR(100) NOT NULL,
    `Description` VARCHAR(256) NOT NULL,
    `IsDeleted` BOOLEAN NOT NULL,
    PRIMARY KEY (`Id`)
) ENGINE = MyISAM DEFAULT CHARSET=utf8;
