export const SERVER_EVENTS = {
  ON_SERVER_START: "ON_SERVER_START",
  ON_SERVER_STOP_SIGNAL: "ON_SERVER_STOP_SIGNAL",
  ON_REQUEST_START: "ON_REQUEST_START",
  ON_REQUEST_END: "ON_REQUEST_END",
  ON_FILTER_FATAL: "ON_FILTER_FATAL",
  ON_FILTER_FAIL: "ON_FILTER_FAIL",
  ON_REQUEST_FATAL: "ON_REQUEST_FATAL",
  ON_PARAM_FATAL: "ON_PARAM_FATAL",
  ON_SIGTERM: "ON_SIGTERM",
  ON_SIGINT: "ON_SIGINT",
  ON_PROCESS_FATAL: "ON_PROCESS_FATAL",
  ON_CORE_CONTROLLER_FATAL: "ON_CORE_CONTROLLER_FATAL",
  ON_CORE_METHOD_FATAL: "ON_CORE_METHOD_FATAL"
};
