ALTER TABLE UserScope ADD CONSTRAINT FK_UserScope_User FOREIGN KEY (UserId) REFERENCES User(Id);
ALTER TABLE UserScope ADD CONSTRAINT FK_UserScope_Scope FOREIGN KEY (ApplicationId) REFERENCES Scope(Id);
