CREATE TABLE `Log` (
    `Id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `Severity` TEXT NOT NULL,
    `ApplicationId` BIGINT UNSIGNED NOT NULL,
    `Message` TEXT NOT NULL,
    `LogDate` DATETIME NOT NULL,
    PRIMARY KEY (`Id`)
) ENGINE = MyISAM DEFAULT CHARSET=utf8;
