CREATE TABLE `UserScope` (
  `Id` VARCHAR(36) NOT NULL,
  `UserId` VARCHAR(36) NOT NULL,
  `ApplicationId` VARCHAR(36) NOT NULL,
  `CreatedAtUtc` DATETIME NOT NULL,
  `CreatedByUserId` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE = MyISAM DEFAULT CHARSET=utf8;
