export const ERROR_CODES = {
  ADD_CONTEXT_TO_USER: "E_ADD_CONTEXT_TO_USER",
  REMOVE_ALL_CONTEXTS_LISTING: "E_REMOVE_ALL_CONTEXTS_LISTING",
  LIST_USERS_FOR_CONTEXT: "E_LIST_USERS_FOR_CONTEXT",
  HAS_USER_CONTEXT: "E_HAS_USER_CONTEXT",
  FIND_USER_APPLICATION_BY_ID: "E_FIND_USER_APPLICATION_BY_ID",
  LIST_USER_CONTEXTS: "E_LIST_USER_CONTEXTS",
  FIND_CONTEXT_TO_REMOVE: "E_FIND_CONTEXT_TO_REMOVE"
};
