export const IDENTIFIER_MIN_LENGTH = 1;
export const IDENTIFIER_MAX_LENGTH = 100;

export const PATCH_FAIL_PAYLOAD_NUMBER_OF_PROPERTIES = 1;
export const PATCH_SUCCESS_PAYLOAD_NUMBER_OF_PROPERTIES = 1;
