import { writeFileSync } from "fs";
import { EOL } from "os";
import { join } from "path";

import { TenantTheme } from "@wraithlight/core.ui.types";
import { dateISOSerialize, utcNow } from "@wraithlight/framework.date";

import { tenantThemeGenerator } from "./generator";

const addHeader = (css: string): string => {
  return [
    "/**",
    "* This is an autogenerated file.",
    "* Do not modify it manually!",
    `* Generated at: ${dateISOSerialize(utcNow())} UTC`,
    "**/",
    css
  ].join(EOL);
};

export const tenantThemeGeneratorFactory = (
  outputDirectory: string
) => (
  theme: TenantTheme
): void => {
  const darkCss_ = tenantThemeGenerator(theme.darkMode);

  // TODO: Use mustache templates instead of this
  const darkCss = ["@media (prefers-color-scheme: dark) {",
  darkCss_.split(EOL).map(m => `  ${m}`).join(EOL),
  "}"
  ].join(EOL);

  const lightCss = tenantThemeGenerator(theme.lightMode);

  const darkOutputFilePath = join(outputDirectory, "theme-dark.css");
  const lightOutputFilePath = join(outputDirectory, "theme-light.css");

  // TODO: https://github.com/wraithlight/wraithlight-mono/issues/1585
  writeFileSync(darkOutputFilePath, addHeader(darkCss));
  writeFileSync(lightOutputFilePath, addHeader(lightCss));
};
