export const ERROR_CODES = {
  CREATE: "E_CREATE",
  UPDATE_BY_ID: "E_UPDATE_BY_ID",
  NOT_FOUND_BY_TOKEN: "E_NOT_FOUND_BY_TOKEN",
  FIND_BY_TOKEN: "E_FIND_BY_TOKEN",
  NOT_FOUND_BY_ID: "E_NOT_FOUND_BY_ID",
  FIND_BY_ID: "E_FIND_BY_ID"
};
