name: "Applications GHA - SWAGGER Schema"
run-name: "SWAGGER SCHEMA"
on: [push, workflow_dispatch]
jobs:
  validate-swagger:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.20.8
        cache: "yarn"
        cache-dependency-path: applications/yarn.lock
    - name: Install packages
      run: yarn
      working-directory: ./applications
    - name: Run validate
      run: yarn validate-swagger-json
      working-directory: ./applications
