name: "Create Release Branch"
run-name: "Release Branch"
on:
  workflow_dispatch:
    inputs:
      source_branch:
        required: true
        default: "main"
      version_number:
        required: true
      folder:
        required: true
        default: 'release'
        type: choice
        options:
        - release
        - canary

env:
  SRC_BRANCH: ${{ github.event.inputs.source_branch }}
  VERSION:    ${{ github.event.inputs.version_number }}
  FOLDER:     ${{ github.event.inputs.folder }}

jobs:
 checkout:
   permissions: read-all
   runs-on: ubuntu-latest

   steps:
     - name: Checkout source branch
       uses: actions/checkout@v4
       with:
         ref: ${{ env.SRC_BRANCH }}

 create-release-branch:
    needs: [checkout]
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        run: |
          echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - name: Publish release branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'refs/heads/${{ env.FOLDER }}/${{ env.DATE }}_${{ env.VERSION }}'
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Update Version
        uses: jaywcjlove/github-action-package@main
        with:
          path: ./applications/package.json
          version: '${{ env.VERSION }}'
      - name: Commit changes
        run: |
          git config --global user.name 'gha'
          git config --global user.email 'noreply@github.com'
          git add .
          git commit -m "chore(*): bump to ${{ env.VERSION }}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          base: dev
          branch: '${{ env.FOLDER }}/${{ env.DATE }}_${{ env.VERSION }}'
          title: 'downmerge: ${{ github.event.inputs.version }} (${{ env.FOLDER }})'