name: "Database GHA - Build"
run-name: "DB BUILD"
on: [push, workflow_dispatch]
jobs:
  dbBuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Run build
      run: bash ${GITHUB_WORKSPACE}/database/build.sh
      working-directory: ./database
