name: "Applications GHA - Docker UM"
run-name: "DOCKER - UM"
on: [push, workflow_dispatch]

env:
  WORK_DIR: applications
  DOCKER_FILE_PATH: apps/user-management/node/Dockerfile
  DOCKER_IMAGE_NAME: um-node

jobs:
  build_docker_image:
    name: Build User Management Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build the Docker image
      working-directory: ${{ env.WORK_DIR }}
      run: docker build . -f ${{ env.DOCKER_FILE_PATH }} -t $DOCKER_IMAGE_NAME

    - name: Remove the local image
      run: docker rmi $DOCKER_IMAGE_NAME
